export const categories = [
  "SIGNATURE BOXES",
  "PROMOTIONS",
  "MAKE IT A MEAL",
  "MIDNIGHT DEALS",
  "EVERYDAY VALUE",
];

export const products = [
  {
    id: 1,
    image: "xs.png",
    title: "Crispy Box",
    desc: "2 Pc Hot & Crispy Chicken, 1 Regular Fries, 1 Regular Drink & 1 Coleslaw.",
    price: "495",
    category: "SIGNATURE BOXES",
  },
  {
    id: 2,
    image: "xs (1).png",
    title: "Boneless Box",
    desc: "4 Zinger Strips + 1 Coleslaw + Fries + Drink + 1 Dip + 1 Dinner Roll.",
    price: "540",
    category: "SIGNATURE BOXES",
  },
  {
    id: 3,
    image: "xs (2).png",
    title: "WOW Box",
    desc: "1 Zinger Burger + 1 Pc Chicken + 1 Fries + 1 Drink + 1 Coleslaw.",
    price: "775",
    category: "SIGNATURE BOXES",
  },
  {
    id: 4,
    image: "xs (3).png",
    title: "Krunch Burger",
    desc: "Enjoy the crispy chicken fillet in a soft bun with spicy mayo and our signature sauce with fresh lettuce.",
    price: "195",
    category: "PROMOTIONS",
  },
  {
    id: 5,
    image: "Rice---Spice-500x360-38e7f70-kfc.png",
    title: "Rice and Spice",
    desc: "Aromatic arabian rice with 6 pcs of hot shot with KFC's famous vietnamese sauce with fresh lettuce..",
    price: "640",
    category: "SIGNATURE BOXES",
  },
  {
    id: 6,
    image: "xs (3).png",
    title: "Krunch Burger",
    desc: "Enjoy the crispy chicken fillet in a soft bun with spicy mayo and our signature sauce with fresh lettuce.",
    price: "440",
    category: "MAKE IT A MEAL",
  },
  {
    id: 7,
    image: "Rice---Spice-500x360-38e7f70-kfc.png",
    title: "Rice and Spice",
    desc: "Aromatic arabian rice with 6 pcs of hot shot with KFC's famous vietnamese sauce with fresh lettuce..",
    price: "540",
    category: "MAKE IT A MEAL",
  },
  {
    id: 8,
    image: "xs (3).png",
    title: "Krunch Burger",
    desc: "Enjoy the crispy chicken fillet in a soft bun with spicy mayo and our signature sauce with fresh lettuce.",
    price: "440",
    category: "MAKE IT A MEAL",
  },
  {
    id: 9,
    image: "Rice---Spice-500x360-38e7f70-kfc.png",
    title: "Rice and Spice",
    desc: "Aromatic arabian rice with 6 pcs of hot shot with KFC's famous vietnamese sauce with fresh lettuce..",
    price: "340",
    category: "MAKE IT A MEAL",
  },
  {
    id: 10,
    image: "Twister-500x360-a32b569-kfc.png",
    title: "Twister",
    desc: "2 zinger strips drizzled with KFC signature pepper mayo, tomatoes and fresh lettuce, all wrapped in a lighty toasted tortilla.    ",
    price: "240",
    category: "MAKE IT A MEAL",
  },
  {
    id: 11,
    image: "Mighty-500x360-a2a5dcd-kfc.png",
    title: "Mighty Zinger",
    desc: "2 whole muscle zingers with KFC's spicy mayo, cheese and fresh lettuce, all bundled in a Mighty bun.",
    price: "320",
    category: "EVERYDAY VALUE",
  },
  {
    id: 12,
    image: "xs (1).png",
    title: "Boneless Box",
    desc: "4 Zinger Strips + 1 Coleslaw + Fries + Drink + 1 Dip + 1 Dinner Roll.",
    price: "430",
    category: "EVERYDAY VALUE",
  },
  {
    id: 13,
    image: "xs (2).png",
    title: "WOW Box",
    desc: "1 Zinger Burger + 1 Pc Chicken + 1 Fries + 1 Drink + 1 Coleslaw.",
    price: "400",
    category: "EVERYDAY VALUE",
  },
  {
    id: 14,
    image: "xs (1).png",
    title: "Boneless Box",
    desc: "4 Zinger Strips + 1 Coleslaw + Fries + Drink + 1 Dip + 1 Dinner Roll.",
    price: "540",
    category: "MAKE IT A MEAL",
  },

  {
    id: 15,
    image: "Value-Bucket-500x360-c5df670-kfc.png",
    title: "Value Bucket",
    desc: "9 Pcs Hot & Crispy Chicken    ",
    price: "400",
    category: "EVERYDAY VALUE",
  },
  {
    id: 16,
    image: "FF3-500x360-909fa80-kfc.png",
    title: "Family Festival 3",
    desc: "4 Zinger Burgers + 4 Pcs Chicken + 2 Dinner Rolls + 1.5 Ltr Drink    ",
    price: "430",
    category: "MIDNIGHT DEALS",
  },
  {
    id: 17,
    image: "Web-956a96b-kfc.png",
    title: "Family + One Ramadan Deal Delivery",
    desc: "3 Zinger Burgers + 3 Chicken Pieces + 1 Rice & Spice + 1.5 Ltr Pepsi + 2 Olpers Flavored Milk Packs + 2 Cake Up cupcakesThis Ramadan at KFC Pakistan we decided to do more than just make our customers #feelgood we are empowering them to do good. Introducing the Family +1 Meal (the +1 meal is designed to be given away) so you can share your iftar with someone in need and feel the gratification of doing good from your own hands.",
    price: "430",
    category: "MIDNIGHT DEALS",
  },

  {
    id: 18,
    image: "Twister-500x360-a32b569-kfc.png",
    title: "Twister",
    desc: "2 zinger strips drizzled with KFC signature pepper mayo, tomatoes and fresh lettuce, all wrapped in a lighty toasted tortilla.    ",
    price: "320",
    category: "MIDNIGHT DEALS",
  },
  {
    id: 19,
    image: "Mighty-500x360-a2a5dcd-kfc.png",
    title: "Mighty Zinger",
    desc: "2 whole muscle zingers with KFC's spicy mayo, cheese and fresh lettuce, all bundled in a Mighty bun.",
    price: "320",
    category: "MIDNIGHT DEALS",
  },
  {
    id: 20,
    image: "xs (1).png",
    title: "Boneless Box",
    desc: "4 Zinger Strips + 1 Coleslaw + Fries + Drink + 1 Dip + 1 Dinner Roll.",
    price: "440",
    category: "MIDNIGHT DEALS",
  },

  {
    id: 21,
    image: "web-2-bb9216b-kfc.jpg",
    title: "6 Pcs Spicy Nuggets",
    desc: "6 Pcs of Spicy Nuggets    ",
    price: "440",
    category: "PROMOTIONS",
  },
  {
    id: 22,
    image: "500x360-b5c9ba6-kfc.png",
    title: "Saucy Wings",
    desc: "Tangy Masala Wings, Thai sweet chilli & Buffalo Wings.    ",
    price: "440",
    category: "PROMOTIONS",
  },
  {
    id: 23,
    image: "Fries-Bucket-with-Dips-500x360-8aac53e-kfc.png",
    title: "French Fries Bucket (Mayo)",
    desc: "Enjoy our amazing bucket of fries with Mayo.    ",
    price: "440",
    category: "PROMOTIONS",
  },

  {
    id: 24,
    image: "Value-Bucket-500x360-c5df670-kfc.png",
    title: "Value Bucket",
    desc: "9 Pcs Hot & Crispy Chicken    ",
    price: "420",
    category: "PROMOTIONS",
  },
  {
    id: 25,
    image: "xs (2).png",
    title: "WOW Box",
    desc: "1 Zinger Burger + 1 Pc Chicken + 1 Fries + 1 Drink + 1 Coleslaw.",
    price: "420",
    category: "PROMOTIONS",
  },
];
